# Generated by Django 4.2.4 on 2023-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
