# Generated by Django 4.2.4 on 2023-09-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_is_bookmarked_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_post',
            field=models.BooleanField(default=True, verbose_name='نمایش پست'),
        ),
    ]
