# Generated by Django 4.2.4 on 2023-09-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_seo_description_post_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.CharField(max_length=120, verbose_name='توضیح کوتاه پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
