# Generated by Django 4.2.4 on 2023-09-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_seo_description_alter_post_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_keywords',
            field=models.CharField(blank=True, default='بازی  - بازی اندروید  - برنامه اندروید - نقد و بررسی - فیم و سریال', max_length=255, null=True, verbose_name='کلمات کلیدی'),
        ),
    ]
