# Generated by Django 4.2.4 on 2023-09-07 06:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_seo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیح کوتاه برای گوگل'),
        ),
    ]
