# Generated by Django 4.2.4 on 2023-08-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'دیدگاه', 'verbose_name_plural': ' دیدگاه ها'},
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pcomment', to='posts.post'),
            preserve_default=False,
        ),
    ]
