# Generated by Django 4.2.4 on 2023-09-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_seo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.CharField(max_length=120, verbose_name='توضیح کوتاه پست'),
        ),
    ]
