# Generated by Django 4.2.4 on 2023-09-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_seo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار'),
        ),
    ]
