# Generated by Django 4.2.4 on 2023-09-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
