# Generated by Django 4.2.4 on 2023-09-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.SlugField(allow_unicode=True, max_length=120, verbose_name='توضیح کوتاه پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.SlugField(allow_unicode=True, max_length=255, verbose_name='عنوان'),
        ),
    ]
