# Generated by Django 4.2.4 on 2023-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_categories_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=1, max_length=120, verbose_name='توضیح کوتاه پست'),
            preserve_default=False,
        ),
    ]
