# Generated by Django 4.2.4 on 2023-09-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_is_membership_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('Published', 'Published')], default='published', max_length=20),
        ),
    ]
