# Generated by Django 4.2.4 on 2023-09-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
