# Generated by Django 4.2.4 on 2023-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_seo_description_alter_post_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Scheduled'), (1, 'Published')], default=1, max_length=20),
        ),
    ]
