# Generated by Django 4.2.4 on 2023-10-04 07:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='محتوای پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='محتوای پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.CharField(max_length=120, null=True, verbose_name='توضیح کوتاه پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='توضیح کوتاه پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'SCHEDULED'), ('1', 'PUBLISHED')], default='1', max_length=20),
        ),
    ]
