# Generated by Django 4.2.4 on 2023-08-24 12:56

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_post_updated_for_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_sub',
            field=models.BooleanField(default=False, verbose_name='زیر مجموعه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
