# Generated by Django 4.2.4 on 2023-08-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_comment_is_reply_remove_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
