# Generated by Django 4.2.4 on 2023-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_comment_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='accepted',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
