# Generated by Django 4.2.4 on 2023-09-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('discount_amount', models.IntegerField(blank=True, null=True)),
                ('tantamount', models.IntegerField(blank=True, null=True)),
                ('use_limit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
