# Generated by Django 4.2.4 on 2023-09-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='tantamount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='سقف مبلع تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='use_limit',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='تعداد استفاده'),
        ),
    ]
