# Generated by Django 4.2.4 on 2023-09-30 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_coupon_options_alter_membership_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
