# Generated by Django 4.2.4 on 2023-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_membership_created_membership_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(default=5000, verbose_name='مفدار تخفیف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_amount',
            field=models.BooleanField(default=1, verbose_name='مبلغی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_percentage',
            field=models.BooleanField(default=0, verbose_name='درصدی'),
            preserve_default=False,
        ),
    ]
