# Generated by Django 4.2.4 on 2023-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'منو', 'verbose_name_plural': 'منو'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
