# Generated by Django 4.2.4 on 2023-09-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_menuitem_options_menuitem_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.CharField(default=1, max_length=1000, verbose_name='لینک صفحه'),
            preserve_default=False,
        ),
    ]
